In [1]:
import numpy as np
import pandas as pd

In [12]:
cands = pd.read_csv('../data/raw/cands22.txt', quotechar="|", header=None)

# regex: sep=r"\,\|"
# skiprows = 851

In [13]:
# help(pd.read_csv)
cands

,0,1,2,3,4,5,6,7,8,9,10,11
0,2022,H0AK00105,N00039029,Thomas Lamb (3),3,AK01,,,,,3N,
1,2022,H0AL01055,N00044245,Jerry Carl (R),R,AL01,AL01,Y,Y,I,RW,
2,2022,H0AL01063,N00044288,Wes Lambert (R),R,AL01,,,,,RN,
3,2022,H0AL01097,N00044750,James Averhart (D),D,AL01,,,,,DN,
4,2022,H0AL02087,N00030768,Martha Roby (R),R,AL02,,,,,RN,
...,...,...,...,...,...,...,...,...,...,...,...,...
8923,2022,S8WI00224,N00041929,Leah Vukmir (R),R,WIS1,,,,,RN,
8924,2022,S8WV00119,N00041293,Paula Jean Swearengin (D),D,WVS2,,,,,DN,
8925,2022,S8WV00127,N00035531,Evan Jenkins (R),R,WVS1,,,,,RN,
8926,2022,S8WV00135,N00041474,Bo Copley (R),R,WVS1,,,,,RN,
8927,2022,S8WV00143,N00012642,Patrick Morrisey (R),R,WVS1,,,,,RN,

In [14]:
# url = "link to data"

votes = pd.read_csv('../data/raw/HSall_votes.csv')

C:\Users\ispea\AppData\Local\Temp\ipykernel_20412\2973816670.py:3: DtypeWarning: Columns (0: prob) have mixed types. Specify dtype option on import or set low_memory=False.
  votes = pd.read_csv('../data/raw/HSall_votes.csv')

In [16]:
votes.head(3).T

                            0                 1                  2
congress                    1                 1                  1
chamber                 House             House              House
rollnumber                  1                 1                  1
icpsr                   154.0             259.0              379.0
cast_code                   6                 9                  1
prob        56.92195016659824  98.3120269302764  98.47231695715722

In [17]:
votes = votes.drop(columns=['prob'])

In [18]:
votes.dtypes

congress        int64
chamber           str
rollnumber      int64
icpsr         float64
cast_code       int64
dtype: object

In [19]:
votes.to_csv("../data/raw/allvotes.csv", index=False)

In [20]:
votes.to_parquet("../data/raw/allvotes.parquet", compression='zstd')

In [22]:
import os
# import time: not necessary bc compute time is visible under each cell

In [23]:
votes_csv = pd.read_csv("../data/raw/allvotes.csv")

In [24]:
votes_parquet = pd.read_parquet("../data/raw/allvotes.parquet")

In [25]:
os.path.getsize("../data/raw/allvotes.csv")

635295102

In [ ]:
os.path.getsize("../data/raw/allvotes.parquet")  # parquet is cool now!!

9312586