In [1]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
botname = 'ds6600'
version = '0.0'
purpose = 'Class demo'
email = 'gsu4aq@virginia.edu'
useragent = f'{botname}/{version} ({purpose}; {email}) python-requests/{requests.__version__}'
headers = {'User_Agent': useragent}

In [3]:
house_committees_url = 'https://clerk.house.gov/committees/'

r = requests.get(house_committees_url, headers=headers)
r

In [4]:
r.text

'<!DOCTYPE html>\r\n<html lang="en" class="no-js">\r\n<head>\r\n   <meta charset="utf-8">\r\n   <meta http-equiv="X-UA-Compatible" content="IE=edge">\r\n   <meta name="viewport" content="width=device-width, initial-scale=1.0">\r\n   <meta name="referrer" content="always">\r\n   <title>Office of the Clerk, U.S. House of Representatives</title>\r\n   <script type="text/javascript" nonce="B2yPHKaXnvFWtRChIbabYmUBFZdVfKKXHbWtWidDVF8">\r\n            window.NREUM||(NREUM={}),__nr_require=function(t,n,e){function r(e){if(!n[e]){var o=n[e]={exports:{}};t[e][0].call(o.exports,function(n){var o=t[e][1][n];return r(o||n)},o,o.exports)}return n[e].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o<e.length;o++)r(e[o]);return r}({1:[function(t,n,e){function r(t){try{s.console&&console.log(t)}catch(n){}}var o,i=t("ee"),a=t(16),s={};try{o=localStorage.getItem("__nr_flags").split(","),console&&"function"==typeof console.log&&(s.console=!0,o.indexOf("dev")!==-1&&(s.dev=!0),o.indexOf("nr_dev")!==-1&&(s.nrDev=!0))}catch(c){}s.nrDev&&i.on("internal-error",function(t){r(t.stack)}),s.dev&&i.on("fn-err",function(t,n,e){r(e.stack)}),s.dev&&(r("NR AGENT IN DEVELOPMENT MODE"),r("flags: "+a(s,function(t,n){return t}).join(", ")))},{}],2:[function(t,n,e){function r(t,n,e,r,s){try{p?p-=1:o(s||new UncaughtException(t,n,e),!0)}catch(f){try{i("ierr",[f,c.now(),!0])}catch(d){}}return"function"==typeof u&&u.apply(this,a(arguments))}function UncaughtException(t,n,e){this.message=t||"Uncaught error with no additional information",this.sourceURL=n,this.line=e}function o(t,n){var e=n?null:c.now();i("err",[t,e])}var i=t("handle"),a=t(17),s=t("ee"),c=t("loader"),f=t("gos"),u=window.onerror,d=!1,l="nr@seenError",p=0;c.features.err=!0,t(1),window.onerror=r;try{throw new Error}catch(h){"stack"in h&&(t(8),t(7),"addEventListener"in window&&t(5),c.xhrWrappable&&t(9),d=!0)}s.on("fn-start",function(t,n,e){d&&(p+=1)}),s.on("fn-err",function(t,n,e){d&&!e[l]&&(f(e,l,function(){return!0}),this.thrown=!0,o(e))}),s.on("fn-end",function(){d&&!this.thrown&&p>0&&(p-=1)}),s.on("internal-error",function(t){i("ierr",[t,c.now(),!0])})},{}],3:[function(t,n,e){t("loader").features.ins=!0},{}],4:[function(t,n,e){function r(t){}if(window.performance&&window.performance.timing&&window.performance.getEntriesByType){var o=t("ee"),i=t("handle"),a=t(8),s=t(7),c="learResourceTimings",f="addEventListener",u="resourcetimingbufferfull",d="bstResource",l="resource",p="-start",h="-end",m="fn"+p,v="fn"+h,w="bstTimer",y="pushState",g=t("loader");g.features.stn=!0,t(6);var b=NREUM.o.EV;o.on(m,function(t,n){var e=t[0];e instanceof b&&(this.bstStart=g.now())}),o.on(v,function(t,n){var e=t[0];e instanceof b&&i("bst",[e,n,this.bstStart,g.now()])}),a.on(m,function(t,n,e){this.bstStart=g.now(),this.bstType=e}),a.on(v,function(t,n){i(w,[n,this.bstStart,g.now(),this.bstType])}),s.on(m,function(){this.bstStart=g.now()}),s.on(v,function(t,n){i(w,[n,this.bstStart,g.now(),"requestAnimationFrame"])}),o.on(y+p,function(t){this.time=g.now(),this.startPath=location.pathname+location.hash}),o.on(y+h,function(t){i("bstHist",[location.pathname+location.hash,this.startPath,this.time])}),f in window.performance&&(window.performance["c"+c]?window.performance[f](u,function(t){i(d,[window.performance.getEntriesByType(l)]),window.performance["c"+c]()},!1):window.performance[f]("webkit"+u,function(t){i(d,[window.performance.getEntriesByType(l)]),window.performance["webkitC"+c]()},!1)),document[f]("scroll",r,{passive:!0}),document[f]("keypress",r,!1),document[f]("click",r,!1)}},{}],5:[function(t,n,e){function r(t){for(var n=t;n&&!n.hasOwnProperty(u);)n=Object.getPrototypeOf(n);n&&o(n)}function o(t){s.inPlace(t,[u,d],"-",i)}function i(t,n){return t[1]}var a=t("ee").get("events"),s=t(19)(a,!0),c=t("gos"),f=XMLHttpRequest,u="addEventListener",d="removeEventListener";n.exports=a,"getPrototypeOf"in Object?(r(document),r(window),r(f.prototype)):f.prototype.hasOwnProperty(u)&&(o(window),o(f.prototype)),a.on(u+"-start",function(t,n){var e=t[1],r=c(e,"nr@wrapped",function(){function t(){if("function"==typeof e.handleEvent)return e.handleEvent.apply(e,arguments)}var n={object:t,"function":e}[typeof e];return n?s(n,"fn-",null,n.name||"anonymous"):e});this.wrapped=t[1]=r}),a.on(d+"-start",function(t){t[1]=this.wrapped||t[1]})},{}],6:[function(t,n,e){var r=t("ee").get("history"),o=t(19)(r);n.exports=r,o.inPlace(window.history,["pushState","replaceState"],"-")},{}],7:[function(t,n,e){var r=t("ee").get("raf"),o=t(19)(r),i="equestAnimationFrame";n.exports=r,o.inPlace(window,["r"+i,"mozR"+i,"webkitR"+i,"msR"+i],"raf-"),r.on("raf-start",function(t){t[0]=o(t[0],"fn-")})},{}],8:[function(t,n,e){function r(t,n,e){t[0]=a(t[0],"fn-",null,e)}function o(t,n,e){this.method=e,this.timerDuration=isNaN(t[1])?0:+t[1],t[0]=a(t[0],"fn-",this,e)}var i=t("ee").get("timer"),a=t(19)(i),s="setTimeout",c="setInterval",f="clearTimeout",u="-start",d="-";n.exports=i,a.inPlace(window,[s,"setImmediate"],s+d),a.inPlace(window,[c],c+d),a.inPlace(window,[f,"clearImmediate"],f+d),i.on(c+u,r),i.on(s+u,o)},{}],9:[function(t,n,e){function r(t,n){d.inPlace(n,["onreadystatechange"],"fn-",s)}function o(){var t=this,n=u.context(t);t.readyState>3&&!n.resolved&&(n.resolved=!0,u.emit("xhr-resolved",[],t)),d.inPlace(t,y,"fn-",s)}function i(t){g.push(t),h&&(x?x.then(a):v?v(a):(E=-E,O.data=E))}function a(){for(var t=0;t<g.length;t++)r([],g[t]);g.length&&(g=[])}function s(t,n){return n}function c(t,n){for(var e in t)n[e]=t[e];return n}t(5);var f=t("ee"),u=f.get("xhr"),d=t(19)(u),l=NREUM.o,p=l.XHR,h=l.MO,m=l.PR,v=l.SI,w="readystatechange",y=["onload","onerror","onabort","onloadstart","onloadend","onprogress","ontimeout"],g=[];n.exports=u;var b=window.XMLHttpRequest=function(t){var n=new p(t);try{u.emit("new-xhr",[n],n),n.addEventListener(w,o,!1)}catch(e){try{u.emit("internal-error",[e])}catch(r){}}return n};if(c(p,b),b.prototype=p.prototype,d.inPlace(b.prototype,["open","send"],"-xhr-",s),u.on("send-xhr-start",function(t,n){r(t,n),i(n)}),u.on("open-xhr-start",r),h){var x=m&&m.resolve();if(!v&&!m){var E=1,O=document.createTextNode(E);new h(a).observe(O,{characterData:!0})}}else f.on("fn-end",function(t){t[0]&&t[0].type===w||a()})},{}],10:[function(t,n,e){function r(t){var n=this.params,e=this.metrics;if(!this.ended){this.ended=!0;for(var r=0;r<d;r++)t.removeEventListener(u[r],this.listener,!1);if(!n.aborted){if(e.duration=a.now()-this.startTime,4===t.readyState){n.status=t.status;var i=o(t,this.lastSize);if(i&&(e.rxSize=i),this.sameOrigin){var c=t.getResponseHeader("X-NewRelic-App-Data");c&&(n.cat=c.split(", ").pop())}}else n.status=0;e.cbTime=this.cbTime,f.emit("xhr-done",[t],t),s("xhr",[n,e,this.startTime])}}}function o(t,n){var e=t.responseType;if("json"===e&&null!==n)return n;var r="arraybuffer"===e||"blob"===e||"json"===e?t.response:t.responseText;return h(r)}function i(t,n){var e=c(n),r=t.params;r.host=e.hostname+":"+e.port,r.pathname=e.pathname,t.sameOrigin=e.sameOrigin}var a=t("loader");if(a.xhrWrappable){var s=t("handle"),c=t(11),f=t("ee"),u=["load","error","abort","timeout"],d=u.length,l=t("id"),p=t(14),h=t(13),m=window.XMLHttpRequest;a.features.xhr=!0,t(9),f.on("new-xhr",function(t){var n=this;n.totalCbs=0,n.called=0,n.cbTime=0,n.end=r,n.ended=!1,n.xhrGuids={},n.lastSize=null,p&&(p>34||p<10)||window.opera||t.addEventListener("progress",function(t){n.lastSize=t.loaded},!1)}),f.on("open-xhr-start",function(t){this.params={method:t[0]},i(this,t[1]),this.metrics={}}),f.on("open-xhr-end",function(t,n){"loader_config"in NREUM&&"xpid"in NREUM.loader_config&&this.sameOrigin&&n.setRequestHeader("X-NewRelic-ID",NREUM.loader_config.xpid)}),f.on("send-xhr-start",function(t,n){var e=this.metrics,r=t[0],o=this;if(e&&r){var i=h(r);i&&(e.txSize=i)}this.startTime=a.now(),this.listener=function(t){try{"abort"===t.type&&(o.params.aborted=!0),("load"!==t.type||o.called===o.totalCbs&&(o.onloadCalled||"function"!=typeof n.onload))&&o.end(n)}catch(e){try{f.emit("internal-error",[e])}catch(r){}}};for(var s=0;s<d;s++)n.addEventListener(u[s],this.listener,!1)}),f.on("xhr-cb-time",function(t,n,e){this.cbTime+=t,n?this.onloadCalled=!0:this.called+=1,this.called!==this.totalCbs||!this.onloadCalled&&"function"==typeof e.onload||this.end(e)}),f.on("xhr-load-added",function(t,n){var e=""+l(t)+!!n;this.xhrGuids&&!this.xhrGuids[e]&&(this.xhrGuids[e]=!0,this.totalCbs+=1)}),f.on("xhr-load-removed",function(t,n){var e=""+l(t)+!!n;this.xhrGuids&&this.xhrGuids[e]&&(delete this.xhrGuids[e],this.totalCbs-=1)}),f.on("addEventListener-end",function(t,n){n instanceof m&&"load"===t[0]&&f.emit("xhr-load-added",[t[1],t[2]],n)}),f.on("removeEventListener-end",function(t,n){n instanceof m&&"load"===t[0]&&f.emit("xhr-load-removed",[t[1],t[2]],n)}),f.on("fn-start",function(t,n,e){n instanceof m&&("onload"===e&&(this.onload=!0),("load"===(t[0]&&t[0].type)||this.onload)&&(this.xhrCbStart=a.now()))}),f.on("fn-end",function(t,n){this.xhrCbStart&&f.emit("xhr-cb-time",[a.now()-this.xhrCbStart,this.onload,n],n)})}},{}],11:[function(t,n,e){n.exports=function(t){var n=document.createElement("a"),e=window.location,r={};n.href=t,r.port=n.port;var o=n.href.split("://");!r.port&&o[1]&&(r.port=o[1].split("/")[0].split("@").pop().split(":")[1]),r.port&&"0"!==r.port||(r.port="https"===o[0]?"443":"80"),r.hostname=n.hostname||e.hostname,r.pathname=n.pathname,r.protocol=o[0],"/"!==r.pathname.charAt(0)&&(r.pathname="/"+r.pathname);var i=!n.protocol||":"===n.protocol||n.protocol===e.protocol,a=n.hostname===document.domain&&n.port===e.port;return r.sameOrigin=i&&(!n.hostname||a),r}},{}],12:[function(t,n,e){function r(){}function o(t,n,e){return function(){return i(t,[f.now()].concat(s(arguments)),n?null:this,e),n?void 0:this}}var i=t("handle"),a=t(16),s=t(17),c=t("ee").get("tracer"),f=t("loader"),u=NREUM;"undefined"==typeof window.newrelic&&(newrelic=u);var d=["setPageViewName","setCustomAttribute","setErrorHandler","finished","addToTrace","inlineHit","addRelease"],l="api-",p=l+"ixn-";a(d,function(t,n){u[n]=o(l+n,!0,"api")}),u.addPageAction=o(l+"addPageAction",!0),u.setCurrentRouteName=o(l+"routeName",!0),n.exports=newrelic,u.interaction=function(){return(new r).get()};var h=r.prototype={createTracer:function(t,n){var e={},r=this,o="function"==typeof n;return i(p+"tracer",[f.now(),t,e],r),function(){if(c.emit((o?"":"no-")+"fn-start",[f.now(),r,o],e),o)try{return n.apply(this,arguments)}catch(t){throw c.emit("fn-err",[arguments,this,t],e),t}finally{c.emit("fn-end",[f.now()],e)}}}};a("actionText,setName,setAttribute,save,ignore,onEnd,getContext,end,get".split(","),function(t,n){h[n]=o(p+n)}),newrelic.noticeError=function(t,n){"string"==typeof t&&(t=new Error(t)),i("err",[t,f.now(),!1,n])}},{}],13:[function(t,n,e){n.exports=function(t){if("string"==typeof t&&t.length)return t.length;if("object"==typeof t){if("undefined"!=typeof ArrayBuffer&&t instanceof ArrayBuffer&&t.byteLength)return t.byteLength;if("undefined"!=typeof Blob&&t instanceof Blob&&t.size)return t.size;if(!("undefined"!=typeof FormData&&t instanceof FormData))try{return JSON.stringify(t).length}catch(n){return}}}},{}],14:[function(t,n,e){var r=0,o=navigator.userAgent.match(/Firefox[\\/\\s](\\d+\\.\\d+)/);o&&(r=+o[1]),n.exports=r},{}],15:[function(t,n,e){function r(t,n){if(!o)return!1;if(t!==o)return!1;if(!n)return!0;if(!i)return!1;for(var e=i.split("."),r=n.split("."),a=0;a<r.length;a++)if(r[a]!==e[a])return!1;return!0}var o=null,i=null,a=/Version\\/(\\S+)\\s+Safari/;if(navigator.userAgent){var s=navigator.userAgent,c=s.match(a);c&&s.indexOf("Chrome")===-1&&s.indexOf("Chromium")===-1&&(o="Safari",i=c[1])}n.exports={agent:o,version:i,match:r}},{}],16:[function(t,n,e){function r(t,n){var e=[],r="",i=0;for(r in t)o.call(t,r)&&(e[i]=n(r,t[r]),i+=1);return e}var o=Object.prototype.hasOwnProperty;n.exports=r},{}],17:[function(t,n,e){function r(t,n,e){n||(n=0),"undefined"==typeof e&&(e=t?t.length:0);for(var r=-1,o=e-n||0,i=Array(o<0?0:o);++r<o;)i[r]=t[n+r];return i}n.exports=r},{}],18:[function(t,n,e){n.exports={exists:"undefined"!=typeof window.performance&&window.performance.timing&&"undefined"!=typeof window.performance.timing.navigationStart}},{}],19:[function(t,n,e){function r(t){return!(t&&t instanceof Function&&t.apply&&!t[a])}var o=t("ee"),i=t(17),a="nr@original",s=Object.prototype.hasOwnProperty,c=!1;n.exports=function(t,n){function e(t,n,e,o){function nrWrapper(){var r,a,s,c;try{a=this,r=i(arguments),s="function"==typeof e?e(r,a):e||{}}catch(f){l([f,"",[r,a,o],s])}u(n+"start",[r,a,o],s);try{return c=t.apply(a,r)}catch(d){throw u(n+"err",[r,a,d],s),d}finally{u(n+"end",[r,a,c],s)}}return r(t)?t:(n||(n=""),nrWrapper[a]=t,d(t,nrWrapper),nrWrapper)}function f(t,n,o,i){o||(o="");var a,s,c,f="-"===o.charAt(0);for(c=0;c<n.length;c++)s=n[c],a=t[s],r(a)||(t[s]=e(a,f?s+o:o,i,s))}function u(e,r,o){if(!c||n){var i=c;c=!0;try{t.emit(e,r,o,n)}catch(a){l([a,e,r,o])}c=i}}function d(t,n){if(Object.defineProperty&&Object.keys)try{var e=Object.keys(t);return e.forEach(function(e){Object.defineProperty(n,e,{get:function(){return t[e]},set:function(n){return t[e]=n,n}})}),n}catch(r){l([r])}for(var o in t)s.call(t,o)&&(n[o]=t[o]);return n}function l(n){try{t.emit("internal-error",n)}catch(e){}}return t||(t=o),e.inPlace=f,e.flag=a,e}},{}],ee:[function(t,n,e){function r(){}function o(t){function n(t){return t&&t instanceof r?t:t?c(t,s,i):i()}function e(e,r,o,i){if(!l.aborted||i){t&&t(e,r,o);for(var a=n(o),s=m(e),c=s.length,f=0;f<c;f++)s[f].apply(a,r);var d=u[g[e]];return d&&d.push([b,e,r,a]),a}}function p(t,n){y[t]=m(t).concat(n)}function h(t,n){var e=y[t];if(e)for(var r=0;r<e.length;r++)e[r]===n&&e.splice(r,1)}function m(t){return y[t]||[]}function v(t){return d[t]=d[t]||o(e)}function w(t,n){f(t,function(t,e){n=n||"feature",g[e]=n,n in u||(u[n]=[])})}var y={},g={},b={on:p,addEventListener:p,removeEventListener:h,emit:e,get:v,listeners:m,context:n,buffer:w,abort:a,aborted:!1};return b}function i(){return new r}function a(){(u.api||u.feature)&&(l.aborted=!0,u=l.backlog={})}var s="nr@context",c=t("gos"),f=t(16),u={},d={},l=n.exports=o();l.backlog=u},{}],gos:[function(t,n,e){function r(t,n,e){if(o.call(t,n))return t[n];var r=e();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(t,n,{value:r,writable:!0,enumerable:!1}),r}catch(i){}return t[n]=r,r}var o=Object.prototype.hasOwnProperty;n.exports=r},{}],handle:[function(t,n,e){function r(t,n,e,r){o.buffer([t],r),o.emit(t,n,e)}var o=t("ee").get("handle");n.exports=r,r.ee=o},{}],id:[function(t,n,e){function r(t){var n=typeof t;return!t||"object"!==n&&"function"!==n?-1:t===window?0:a(t,i,function(){return o++})}var o=1,i="nr@id",a=t("gos");n.exports=r},{}],loader:[function(t,n,e){function r(){if(!E++){var t=x.info=NREUM.info,n=p.getElementsByTagName("script")[0];if(setTimeout(u.abort,3e4),!(t&&t.licenseKey&&t.applicationID&&n))return u.abort();f(g,function(n,e){t[n]||(t[n]=e)}),c("mark",["onload",a()+x.offset],null,"api");var e=p.createElement("script");e.src="https://"+t.agent,n.parentNode.insertBefore(e,n)}}function o(){"complete"===p.readyState&&i()}function i(){c("mark",["domContent",a()+x.offset],null,"api")}function a(){return O.exists&&performance.now?Math.round(performance.now()):(s=Math.max((new Date).getTime(),s))-x.offset}var s=(new Date).getTime(),c=t("handle"),f=t(16),u=t("ee"),d=t(15),l=window,p=l.document,h="addEventListener",m="attachEvent",v=l.XMLHttpRequest,w=v&&v.prototype;NREUM.o={ST:setTimeout,SI:l.setImmediate,CT:clearTimeout,XHR:v,REQ:l.Request,EV:l.Event,PR:l.Promise,MO:l.MutationObserver};var y=""+location,g={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",agent:"js-agent.newrelic.com/nr-1118.min.js"},b=v&&w&&w[h]&&!/CriOS/.test(navigator.userAgent),x=n.exports={offset:s,now:a,origin:y,features:{},xhrWrappable:b,userAgent:d};t(12),p[h]?(p[h]("DOMContentLoaded",i,!1),l[h]("load",r,!1)):(p[m]("onreadystatechange",o),l[m]("onload",r)),c("mark",["firstbyte",s],null,"api");var E=0,O=t(18)},{}]},{},["loader",2,10,4,3]);\r\n        ;NREUM.info={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",licenseKey:"9993044f26",applicationID:"1120177994",sa:1}\r\n   </script>\r\n\r\n   <!-- Google tag (gtag.js) -->\r\n   <script async src="https://www.googletagmanager.com/gtag/js?id=G-N512ZD1JJT"></script>\r\n   <script type="text/javascript" nonce="B2yPHKaXnvFWtRChIbabYmUBFZdVfKKXHbWtWidDVF8">\r\n      window.dataLayer = window.dataLayer || [];\r\n      function gtag() { dataLayer.push(arguments); }\r\n      gtag(\'js\', new Date());\r\n      gtag(\'config\', \'G-N512ZD1JJT\');\r\n   </script>\r\n\r\n   \r\n\r\n   <link rel="stylesheet" href="/assets/css/site.min.css" />\r\n   <link rel="stylesheet" href="/assets/css/introjs.min.css" />\r\n\r\n   <!-- Bitmovin Player -->\r\n   <script type="text/javascript" src="/scripts/bitmovinplayer.js" nonce="B2yPHKaXnvFWtRChIbabYmUBFZdVfKKXHbWtWidDVF8"></script>\r\n\r\n   <script type="text/javascript" nonce="B2yPHKaXnvFWtRChIbabYmUBFZdVfKKXHbWtWidDVF8">(function (H) { H.className = H.className.replace(/\\bno-js\\b/, \'js\') })(document.documentElement)</script>\r\n   <script type="text/javascript" src="/scripts/modernizr-custom.js" nonce="B2yPHKaXnvFWtRChIbabYmUBFZdVfKKXHbWtWidDVF8"></script>\r\n\r\n   <!--[if lte IE9]>\r\n         <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>\r\n         <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>\r\n       <![endif]-->\r\n\r\n      <link rel="stylesheet" href="/assets/vendor/Keyoti_SearchEngine_Web_Common/SearchUnit.css" />\r\n      <script src="/assets/vendor/Keyoti_SearchEngine_Web_Common/searchunit.js" nonce="B2yPHKaXnvFWtRChIbabYmUBFZdVfKKXHbWtWidDVF8"></script>\r\n\r\n   <script src="/scripts/main.min.js" nonce="B2yPHKaXnvFWtRChIbabYmUBFZdVfKKXHbWtWidDVF8"></script>\r\n\r\n   \r\n</head>\r\n<body id="homepage" class="in-session">\r\n\r\n    \r\n<header id="header" class="navbar-fixed-top">\r\n\r\n    <div class="container">\r\n        <div class="row">\r\n            <div class="col-sm-6 hidden-xs logo">\r\n                <a href="/">\r\n                    <img src="/assets/img/clerk-logo-web.svg" title="Office of the Clerk, U.S. House of Representatives" alt="Office of the Clerk, U.S. House of Representatives" />\r\n                </a>\r\n            </div>\r\n            <div class="hidden-xs col-sm-6 hidden-print">\r\n                <div class="header-search-grp">\r\n                    <ul class="inline-list">\r\n                        <li><a href="/Members#FindRepresentative" class="partial-view-link" title="Find Your Representative">Find Your Representative</a></li>\r\n                    </ul>\r\n                    <div class="col-sm-12" style="padding-right: 5px">\r\n<form action="/Search" class="search expanded" id="searchform" method="get">                            <label for="clerk-search">Search Office of the Clerk</label>\r\n                            <input type="text" name="searchQuery" class="site-search" autocomplete="off" />\r\n                            <i class="fa fa-search">&nbsp;</i>\r\n                            <input type="submit" value="Submit">\r\n</form>                    </div>\r\n\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div class="search-container"></div>\r\n\r\n    \r\n      <!--keyoti_search_ignore_begin-->\r\n      <nav id="main-navbar" class="navbar navbar-static" role="navigation" arial-label="Main Menu">\r\n         <div class="container">\r\n            <div class="row">\r\n               <div class="navbar-header">\r\n                  <div class="logo visible-xs">\r\n                     <a href="/" title="Office of the Clerk, U.S. House of Representatives">\r\n                        <img src="/assets/img/clerk-logo-web.svg" title="Office of the Clerk, U.S. House of Representatives" alt="Office of the Clerk, U.S. House of Representatives" />\r\n                     </a>\r\n                  </div>\r\n                  <button class="navbar-toggle" ty

In [5]:
mysoup = BeautifulSoup(r.text, 'html.parser')

Anatomy of HTML

```
<tag attribute=="value"> navigable string </tag>

```

In [6]:
mylist = mysoup.find_all('a', attrs = {'class': 'library-committeePanel-subItems'})

In [7]:
{'url': 'https://clerk.house.gov' + mylist[0]['href'], 'committee_name': mylist[0].text.strip()}

{'url': 'https://clerk.house.gov/committees/AG22',
 'committee_name': 'Commodity Markets, Digital Assets, and Rural Development'}

In [8]:
committee_df = pd.DataFrame([{'url': 'https://clerk.house.gov' + x['href'], 'committee_name': x.text.strip()} for x in mylist])
committee_df

,url,committee_name
0,https://clerk.house.gov/committees/AG22,"Commodity Markets, Digital Assets, and Rural D..."
1,https://clerk.house.gov/committees/AG14,"Conservation, Research, and Biotechnology"
2,https://clerk.house.gov/committees/AG15,Forestry and Horticulture
3,https://clerk.house.gov/committees/AG16,"General Farm Commodities, Risk Management, and..."
4,https://clerk.house.gov/committees/AG29,"Livestock, Dairy, and Poultry"
...,...,...
105,https://clerk.house.gov/committees/IG04,Defense Intelligence and Overhead Architecture
106,https://clerk.house.gov/committees/IG06,National Intelligence Enterprise
107,https://clerk.house.gov/committees/IG02,National Security Agency and Cyber
108,https://clerk.house.gov/committees/IG11,Open Source Intelligence
109,https://clerk.house.gov/committees/IG09,Oversight and Investigations

In [9]:
url = committee_df['url'][0]

In [10]:
r = requests.get(url, headers=headers)
r

In [11]:
mysoup = BeautifulSoup(r.text, 'html.parser')

In [15]:
mylist = mysoup.find_all('a', attrs = {'title':'View Profile'})
print(mylist)
#bioguideIds = [x['href'].replace('/Members', '') for x in mylist]
#pd.DataFrame({'committee': committee_df['committee_name'][0], 'bioguideId': bioguideIds})

[<a class="library-link" href="/Members/J000301" role="link" title="View Profile">
<span style="text-decoration: none;"> Dusty Johnson</span>, SD                           </a>, <a class="library-link" href="/Members/R000612" role="link" title="View Profile">
<span style="text-decoration: none;"> John W. Rose</span>, TN                           </a>, <a class="library-link" href="/Members/L000491" role="link" title="View Profile">
<span style="text-decoration: none;"> Frank D. Lucas</span>, OK                           </a>, <a class="library-link" href="/Members/S001189" role="link" title="View Profile">
<span style="text-decoration: none;"> Austin Scott</span>, GA                           </a>, <a class="library-link" href="/Members/R000603" role="link" title="View Profile">
<span style="text-decoration: none;"> David Rouzer</span>, NC                           </a>, <a class="library-link" href="/Members/M000871" role="link" title="View Profile">
<span style="text-decoration: none;"> Tracey Mann</span>, KS                           </a>, <a class="library-link" href="/Members/C001039" role="link" title="View Profile">
<span style="text-decoration: none;"> Kat Cammack</span>, FL                           </a>, <a class="library-link" href="/Members/F000475" role="link" title="View Profile">
<span style="text-decoration: none;"> Brad Finstad</span>, MN                           </a>, <a class="library-link" href="/Members/N000193" role="link" title="View Profile">
<span style="text-decoration: none;"> Zachary Nunn</span>, IA                           </a>, <a class="library-link" href="/Members/B001327" role="link" title="View Profile">
<span style="text-decoration: none;"> Robert P. Bresnahan, Jr.</span>, PA                           </a>, <a class="library-link" href="/Members/M001233" role="link" title="View Profile">
<span style="text-decoration: none;"> Mark B. Messmer</span>, IN                           </a>, <a class="library-link" href="/Members/T000490" role="link" title="View Profile">
<span style="text-decoration: none;"> David J. Taylor</span>, OH                           </a>, <a class="library-link" href="/Members/D000230" role="link" tabindex="0" title="View Profile">
<span style="font-style: italic;"> Donald G. Davis</span>, NC                           </a>, <a class="library-link" href="/Members/B001315" role="link" tabindex="0" title="View Profile">
<span style="font-style: italic;"> Nikki Budzinski</span>, IL                           </a>, <a class="library-link" href="/Members/J000309" role="link" tabindex="0" title="View Profile">
<span style="font-style: italic;"> Jonathan L. Jackson</span>, IL                           </a>, <a class="library-link" href="/Members/T000488" role="link" tabindex="0" title="View Profile">
<span style="font-style: italic;"> Shri Thanedar</span>, MI                           </a>, <a class="library-link" href="/Members/G000605" role="link" tabindex="0" title="View Profile">
<span style="font-style: italic;"> Adam Gray</span>, CA                           </a>, <a class="library-link" href="/Members/M001237" role="link" tabindex="0" title="View Profile">
<span style="font-style: italic;"> Kristen McDonald Rivet</span>, MI                           </a>, <a class="library-link" href="/Members/F000481" role="link" tabindex="0" title="View Profile">
<span style="font-style: italic;"> Shomari Figures</span>, AL                           </a>, <a class="library-link" href="/Members/V000138" role="link" tabindex="0" title="View Profile">
<span style="font-style: italic;"> Eugene Simon Vindman</span>, VA                           </a>, <a class="library-link" href="/Members/M001231" role="link" tabindex="0" title="View Profile">
<span style="font-style: italic;"> John W. Mannion</span>, NY                           </a>, <a class="library-link" href="/Members/M001232" role="link" tabindex="0" title="View Profile">
<span style="font-style: italic;"> April McClain Delaney</span>, MD                           </a>]

In [13]:
def congress_spider(url, committee):
    r = requests.get(url, headers=headers)
    mysoup = BeautifulSoup(r.text, 'html.parser')
    mylist = mysoup.find_all('a', attrs = {'title':'View Profile'})
    bioguideIds = [x['href'].replace('/Members', '') for x in mylist]
    return {'committee': committee, 'bioguideId': bioguideIds}

In [14]:
full_committee_list = [congress_spider(u, c) for u, c in zip(committee_df['url'], committee_df['committee_name'])]

KeyboardInterrupt:

In [ ]:
list_of_dfs = [pd.DataFrame(x) for x in full_committee_list]
full_df = pd.concat(list_of_dfs)
full_df

                                            committee bioguideId
0   Commodity Markets, Digital Assets, and Rural D...   /J000301
1   Commodity Markets, Digital Assets, and Rural D...   /R000612
2   Commodity Markets, Digital Assets, and Rural D...   /L000491
3   Commodity Markets, Digital Assets, and Rural D...   /S001189
4   Commodity Markets, Digital Assets, and Rural D...   /R000603
..                                                ...        ...
7                            Open Source Intelligence   /C001121
8                            Open Source Intelligence   /Q000023
9                            Open Source Intelligence   /C001068
0                        Oversight and Investigations   /J000304
1                        Oversight and Investigations   /C001091

[1681 rows x 2 columns]